name: 'GitHub Organization Readme Badge Generator'
description: "An action to create markdown badges for your GitHub organization's README.md file"

branding:
  icon: 'award'
  color: 'blue'

inputs:
  organization:
    description: 'The GitHub organization to query'
    required: true
    default: '${{ github.repository_owner }}'
  token:
    description: 'PAT or GitHub App token to query the GitHub API'
    required: true
    default: '${{ github.token }}'
  graphql_url:
    description: 'The URL to the GitHub GraphQL API endpoint'
    required: true
    default: '${{ github.graphql_url }}' # https://api.github.com/graphql
  days:
    description: 'For stats that have a date window, the number of days to query for'
    required: true
    default: '30'
outputs:
  badges:
    description: 'The badge markdown to add to your README.md file'

runs:
  using: 'node20'
  main: 'dist/index.js'
